# TODO on gitlab:
# Repo Settings ->
#   Repository ->
#     Protected Branches ->
#       Unprotect master (or whichever) branch
#
# TODO on github:
# store all necessary variables as secrets, including gitlab password (here as
# GLPW)

name: push-to-gitlab

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    # push won't mirror on gitlab if commit message contains "[nogl]"
    if: "!(contains(github.event.head_commit.message, '[nogl]'))"

    steps:
    - uses: actions/checkout@v2

    - name: Git setup
      run: |
          sudo git config --global user.name ${{secrets.UNAME}}
          sudo git config --global user.email ${{secrets.EMAIL}}
          sudo git clone https://${{secrets.UNAME}}:${{secrets.GH_TOKEN}}@github.com/mpadge/pkgreport
          sudo git fetch --unshallow origin
          sudo git remote add gitlab https://${{secrets.UNAME}}:${{secrets.GLPW}}@gitlab.com/mpadge/pkgreport.git
          sudo git push gitlab master
